[package]
name = "ymfm-sys"
version = "0.2.0"
edition = "2024"
description = "Rust bindings to the ymfm FM sound chip emulation library"
license = "BSD-3-Clause"
authors = ["h1romas4 <h1romas4@gmail.com>"]
homepage = "https://github.com/h1romas4"
repository = "https://github.com/h1romas4/ymfm-sys"
documentation = "https://docs.rs/ymfm-sys"
readme = "README.md"
keywords = ["vgm", "sound", "audio"]
exclude = [
	".github",
	".gitmodules",
	"Cargo.lock",
	"CMakeLists.txt",
]

[dependencies]
cxx = "1"

[build-dependencies]
cc = "1.4.2"
cxx-build = "1.0.198"
