[package]
name = "ymfm-sys"
version = "0.1.0"
edition = "2024"
description = "Rust bindings to the ymfm FM sound chip emulation library"
license = "BSD-3-Clause"
repository = "https://github.com/h1romas4/ymfm-sys"
documentation = "https://docs.rs/ymfm-sys"
exclude = [
	".gitmodules",
	"Cargo.lock",
	"CMakeLists.txt",
]

[dependencies]
cxx = "1.0.198"

[build-dependencies]
cc = "1.4.2"
cxx-build = "1.0.198"
