name: Build-Release

on:
  workflow_call:
    inputs:
      release:
        description: "release"
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v5
        id: cache-toolchaine
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Rust Toolchain Setup
        run: |
          rustup toolchain install 1.97.1 --profile minimal --no-self-update
          rustup default 1.97.1

      - name: Format
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test --all-targets

      - name: Test (rustdoc)
        run: cargo test --doc

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Compile
        run: cargo build --release
